# Default values for mleshchenko-app.

app:
  name: application
  servicePort: 80
  image: iangodbx/mleshchenko_application
  tag: 1.0.1
  resources:
    enabled: true
    requests:
      memory: "64Mi" 
      cpu: "200m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  bgColor: "teal"
  failFlag: "false"

ingress:
  enabled: true
  name: nginx
  host: mleshchenko.application.com
  port: 80

pvc:
  name: mongo-pvc
  storage: 500Mi
  storageClass: local-path

mongo:
  name: mongo
  image: mongo
  tag: latest
  resources:
    enabled: true
    requests:
      memory: "64Mi" 
      cpu: "200m"
    limits:
      memory: "128Mi"
      cpu: "500m"

pv:
  name: mongo-pv
  storage: 1Gi
  reclaimPolicy: Retain

