apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}
data:
  MONGO_HOST: "mongo"
  MONGO_PORT: "27017"
  BG_COLOR: "{{ .Values.app.bgColor }}"
  FAIL_FLAG: "{{ .Values.app.failFlag }}"