apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}
  labels:
    app: {{ .Values.mongo.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.mongo.name }}
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017